### ISSUE TITLE
Broken Install of Cockpit with Addon and no declaration of helpers in config.yaml

### ISSUE THREAD

**Issue by colinappnovation** [pauloamgomes/CockpitCMS-Helpers#1]
Noticed that with this addon added for the first time on a fresh install without the necessary YAML configuration in place

`
helpers:
  environment: local
`
Results in the CMS reporting something has gone wrong.

**Comment by colinappnovation** [comment]
If one then adds the configuration, all is well. Secondly, if you then remove config the addon behaves correctly with no "Oops something has gone wrong message"

**Comment by pauloamgomes** [comment]
Hey @colinappnovation , seems already fixed, can you kindly confirm?

**Comment by sh1r00** [comment]
Hi,
I just tried installing this addon and im stuck at at the same point. When updating the config/config.yaml file to include 
`helpers: environment: local`
I get, Fatal Error: Too many keys: environment: local. Error at /lib/spyc.php line 1061.

It looks like this file combs the yaml file and ensures a key value pair is met, and the multiple keys are setting off the error. How should I proceed here?
