### ISSUE TITLE
Add a CLI command to set the master API key

### ISSUE THREAD

**Issue by Crease29** [pauloamgomes/CockpitCMS-Helpers#2]
I'm deploying cockpit with GitLab CI/CD and would like to be able to set the master API key of my instance via CLI command so I can set it in the deployment.

**Comment by pauloamgomes** [comment]
Hey @Crease29 , yeah, that can be handy, check the readme for details.

**Comment by Crease29** [comment]
Thank you very much, @pauloamgomes !
