### ISSUE TITLE
Undefined getCollectionName() when running update collection 

### ISSUE THREAD

**Issue by slowdub** [pauloamgomes/CockpitCMS-Helpers#3]
When running:
`./cp update-collection --name saints`

I'm getting an error:
`Fatal error: Uncaught Error: Call to undefined method MongoLite\Collection::getCollectionName()`

It's coming from here:
https://github.com/pauloamgomes/CockpitCMS-Helpers/blob/master/cli/update-collection.php#L31
but `$collection_name` seems to be anyway unused?

**Comment by pauloamgomes** [comment]
Thanks @Blistok , that line is not required, but in theory you should not get the error! in such case removed it, can you confirm it works now?

**Comment by slowdub** [comment]
@pauloamgomes yep, all good now - thanks!

I'm not sure why it was failing, other than it was complaining about non-existing `getCollectionName()` method. I'm using latest cockpit (next branch).
