### ISSUE TITLE
Localised field values are not saved

### ISSUE THREAD

**Issue by tanc** [pauloamgomes/CockpitCMS-Helpers#5]
With this addon enabled it seems that localised field values can not be saved.

To reproduce:

- create a collection with a localisable field
- create some content
- switch to a different language in the editor
- update the localised field value
- save the content
- re-edit the content
- switch between languages and notice the localised value is missing

This also means that when running the cli command `update-collection` the localised values are stripped out.

**Comment by pauloamgomes** [comment]
Hey @tanc , thanks for reporting the issue! That happens just with addon enabled or with some of the addon specific configurations active?

**Comment by tanc** [comment]
hi @pauloamgomes I don't think I enabled anything specific... I'm nervous now of re-enabling the addon on this live site in case of data loss. I'll try and set it up locally to see whether I can replicate simply and will report back.

**Comment by pauloamgomes** [comment]
Yeah, I never tested it on a cockpit installation with localized fields, I'll try to check and replicate soon.

**Comment by kkudr** [comment]
That happens not only with localized fields, also with fields like *_slug or *_locale_slug. 

I created fork that fixed it:
[https://github.com/kkudr/CockpitCMS-Helpers/commit/046b91d23c75ac35e56cd6b6274b5b77693fd173](https://github.com/kkudr/CockpitCMS-Helpers/commit/046b91d23c75ac35e56cd6b6274b5b77693fd173)

@pauloamgomes, can you see my solution and fix issue in this repo?

**Comment by pauloamgomes** [comment]
Thanks @kkudr , I'll take a look... you can also do a PR
