### ISSUE TITLE
Sortable collections order and position break when editing 

### ISSUE THREAD

**Issue by goggi** [pauloamgomes/CockpitCMS-Helpers#7]
Hi! 
Thanks for the addon!

I noticed that sortable collections will break due to the "remove fields that doesnt exist anymore" function. 

Simple fix: 
Add **_o & _pid** 
To helpers/actions.php Line 48: 
$core_fields = ['_id', '_mby', '_by', '_modified', '_created'**, '_o', '_pid'**];

Cheers!

**Comment by pauloamgomes** [comment]
Hey @goggi , thanks for the catch-up, updated!
